import { StyleSheet } from 'react-native';

// EXTERNAL STYLE: file terpisah dari app/index.tsx.
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F6F8FB' },
  content: { paddingHorizontal: 20, paddingTop: 48, paddingBottom: 40 },
  topBar: { flexDirection: 'row', alignItems: 'center', marginBottom: 22, gap: 10 },
  logoIcon: { width: 44, height: 44, borderRadius: 13, backgroundColor: '#0D9488', alignItems: 'center', justifyContent: 'center' },
  brand: { fontSize: 24, fontWeight: '800', color: '#142238' },
  brandCaption: { color: '#798596', fontSize: 12 },
  hero: { backgroundColor: '#0D9488', padding: 22, borderRadius: 22, minHeight: 209, overflow: 'hidden', justifyContent: 'center' },
  heroEyebrow: { fontSize: 11, fontWeight: '800', color: '#C5F9F1', letterSpacing: 1.1 },
  heroTitle: { color: '#FFFFFF', fontSize: 27, fontWeight: '800', lineHeight: 33, marginTop: 9 },
  heroDescription: { color: '#E7FFFA', fontSize: 12.5, lineHeight: 19, marginTop: 8, maxWidth: '85%' },
  heroChip: { marginTop: 15, alignSelf: 'flex-start', backgroundColor: '#E7FFFA', borderRadius: 30, flexDirection: 'row', alignItems: 'center', paddingVertical: 7, paddingHorizontal: 11, gap: 6 },
  heroChipText: { fontSize: 11, fontWeight: '700', color: '#075E53' },
  heroDecoration: { position: 'absolute', right: -16, top: -8, opacity: 0.14 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 27, marginBottom: 13 },
  sectionTitle: { fontSize: 19, fontWeight: '800', color: '#152238' },
  sectionCaption: { fontSize: 12, color: '#7C899A' },
  serviceCard: { backgroundColor: '#FFFFFF', borderRadius: 17, padding: 14, flexDirection: 'row', alignItems: 'center', marginBottom: 11, gap: 11 },
  serviceIcon: { width: 48, height: 48, borderRadius: 13, backgroundColor: '#E4F7F4', justifyContent: 'center', alignItems: 'center' },
  serviceInfo: { flex: 1 },
  serviceName: { fontSize: 14, fontWeight: '800', color: '#1D2D42' },
  serviceDescription: { fontSize: 11, color: '#7D8794', marginTop: 3 },
  servicePrice: { fontSize: 12.5, fontWeight: '800', color: '#0D9488', marginTop: 7 },
  formCard: { padding: 18, backgroundColor: '#FFFFFF', borderRadius: 18, borderColor: '#E4E8EF', borderWidth: 1 },
  label: { color: '#334155', fontWeight: '700', fontSize: 12, marginBottom: 8 },
  input: { backgroundColor: '#F8FAFC', borderColor: '#E2E8F0', borderWidth: 1, paddingHorizontal: 13, paddingVertical: 12, borderRadius: 10, color: '#172438', fontSize: 14, marginBottom: 17 },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 5, paddingBottom: 16 },
  priceLabel: { fontSize: 13, color: '#687588' },
  priceValue: { fontSize: 21, color: '#0D9488', fontWeight: '800' },
  orderButton: { backgroundColor: '#0D9488', borderRadius: 11, paddingVertical: 15, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 9 },
  orderButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  footnote: { color: '#8A97A7', fontSize: 10.5, textAlign: 'center', marginTop: 12 },
  footer: { textAlign: 'center', color: '#98A2AF', fontSize: 11, marginTop: 25 },
});
